.class public interface abstract Landroidx/compose2/runtime/internal/ComposableLambda;
.super Ljava/lang/Object;
.source "ComposableLambda.jvm.kt"

# interfaces
.implements Lkotlin2/jvm/functions/Function2;
.implements Lkotlin2/jvm/functions/Function3;
.implements Lkotlin2/jvm/functions/Function4;
.implements Lkotlin2/jvm/functions/Function5;
.implements Lkotlin2/jvm/functions/Function6;
.implements Lkotlin2/jvm/functions/Function7;
.implements Lkotlin2/jvm/functions/Function8;
.implements Lkotlin2/jvm/functions/Function9;
.implements Lkotlin2/jvm/functions/Function10;
.implements Lkotlin2/jvm/functions/Function11;
.implements Lkotlin2/jvm/functions/Function13;
.implements Lkotlin2/jvm/functions/Function14;
.implements Lkotlin2/jvm/functions/Function15;
.implements Lkotlin2/jvm/functions/Function16;
.implements Lkotlin2/jvm/functions/Function17;
.implements Lkotlin2/jvm/functions/Function18;
.implements Lkotlin2/jvm/functions/Function19;
.implements Lkotlin2/jvm/functions/Function20;
.implements Lkotlin2/jvm/functions/Function21;


# annotations
.annotation runtime Landroidx/compose2/runtime/ComposeCompilerApi;
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Ljava/lang/Object;",
        "Lkotlin2/jvm/functions/Function2<",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function3<",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function4<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function5<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function6<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function7<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function8<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function9<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function10<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function11<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function13<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function14<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function15<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function16<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function17<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function18<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function19<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function20<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;",
        "Lkotlin2/jvm/functions/Function21<",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Ljava/lang/Object;",
        "Landroidx/compose2/runtime/Composer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Integer;",
        "Ljava/lang/Object;",
        ">;"
    }
.end annotation
